### ISSUE TITLE
Add ability to configure colors with highlight groups

### ISSUE THREAD

**Issue by mehalter** [s1n7ax/nvim-window-picker#12]
I would love the ability to set highlight groups at the colorscheme level to control the colors between my different themes rather than setting them with the `setup({...})` function!

**Comment by rebelot** [comment]
I'd like to support window picker in Kanagawa, since it is a useful dependency of NeoTree. However, at the moment it is not possible. I think the plugin should use `default` hlgroups so that if a colorscheme already defines them, they won't be overwritten. This is relevant in a world where almost all plugins are lazy-loaded, so it is important that the colorscheme is loaded _before_ every other plugin. Plugins just need to be smart with hl definitions, extrapolating colors from defined hlgroups.
Personally, I think that the options `fg` and `{current,other}_win_hl_color` could be ditched entirely. Instead, define `WindowPicker` and `WindowPickerNC` default links to `StatusLine` and `StatusLineNC`. If you'd like to provide some "change highlights on the fly" functionality, add an `highlight_function` option that takes `winid` as argument and returns a table compliant for `nvim_set_hl`. my 2 cents.

**Comment by s1n7ax** [comment]
Now you can use folllowing highlights.

`WindowPickerStatusLine`, `WindowPickerStatusLineNC`, `WindowPickerWinBar`, `WindowPickerWinBarNC`

**Comment by mehalter** [comment]
@s1n7ax I just tried this actually and it doesn't seem to work

**Comment by s1n7ax** [comment]
pick_window() creating a new picker on every call so probably highlights are being overidden. Will look into it

**Comment by mehalter** [comment]
@s1n7ax maybe the best way to do this is to check if the highlight group already exists and if it does, then don't set it at all

**Comment by s1n7ax** [comment]
Now this branch will uses the global highlights if exists. Creates the highlights only in setup call. Planning override highlights when passed to pick_window() as a parameter using highlight namespaces. At the moment it doen't work though.

**Comment by s1n7ax** [comment]
I was going to use a different namespace for the highlights that's being passed to the pick_window() function but it doesn't seem to work.

I have this to add `Test` highlight to current window(0th window).

```lua
local nsp = vim.api.nvim_create_namespace('test')

vim.api.nvim_set_hl(nsp, 'Test', { fg = 'red', bg = 'green' })
vim.api.nvim_win_set_hl_ns(0, nsp)

vim.print(vim.api.nvim_get_hl(nsp, { name = 'Test' }))
```

Upon printing the highlight, it returns the correct colors

```
{
  bg = 32768,
  fg = 16711680
}
```

Though running `hi Test` returns following.

```
Test          xxx cleared
```

Does anybody have any knowlage of this?

**Comment by mehalter** [comment]
Just tested and works perfectly!
